# Generated by Django 3.2.4 on 2021-06-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_auto_20210605_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='business_desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(default='wangechik@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='neighbourhood.profile'),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hood', to='neighbourhood.neighbourhood'),
        ),
    ]
